### ISSUE TITLE
Minor documentation improvements

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit.com#130]
Hi,

Those are just ideas on ways to improve `pre-commit` documentation / ergonomy:

- I think there is an empty bullet in http://pre-commit.com#filtering-files-with-types
That's because the closing `<li>` there is missing a backslash: https://github.com/pre-commit/pre-commit.github.io/blob/real_master/index.mako#L801

- maybe document `additional_dependencies` format for each language that support it

- it could be handy on the `hooks.html` page to include the hooks languages

- maybe explain that `pre-commit install` writes in `.git/hooks/pre-commit`

- I think `fail_fast` isn't documented yet ;)

- and finally, just a thought : shouldn't the `script` & `system` hooks be merged ?
Maybe we could simply require that scripts paths start with `./` ?

**Comment by asottile** [comment]
- https://github.com/pre-commit/pre-commit.github.io/commit/721b6a1c1f7cb9d2b77cdc44f20f8666ac565569
- yes, that's probably a good idea
- Is the language that a hook is implemented in actually important?  pre-commit is _supposed_ to make that irrelevant
- It's not always `.git/hooks/pre-commit` (submodules, custom `GIT_DIR`, etc.).  PRs welcome if you think you can improve the current verbiage though :)
- heh, neither is global `exclude` nor the new configuration format -- I've been meaning to add a section about that.
- I think merging them actually creates *more* confusion -- it also makes it difficult to differentiate between the *current* repository and a hook repository (is `./` `os.getcwd()/...` or `hook-repo/...`?).

**Comment by Lucas-C** [comment]
> Is the language that a hook is implemented in actually important? pre-commit is _supposed_ to make that irrelevant

Yes I think it, because:
- Docker based hooks require a Docker engine
- Go hooks require Go installed.
Same for Ruby & Swift I guess, even if I never used them

For the rest, I don't want to pressure you, there's no hurry :)
I may send a PR to suggest some wording changes

**Comment by asottile** [comment]
Sweet, if you want to try and take a stab at the language bits, the code for that [sits here](https://github.com/pre-commit/pre-commit.github.io/blob/721b6a1c1f7cb9d2b77cdc44f20f8666ac565569/make_templates.py#L21-L26) and [here](https://github.com/pre-commit/pre-commit.github.io/blob/721b6a1c1f7cb9d2b77cdc44f20f8666ac565569/hooks.mako#L21-L30).

**Comment by Lucas-C** [comment]
Sure. You can assign this to me

**Comment by asottile** [comment]
I think this has been addressed -- thanks again!
