### ISSUE TITLE
A wordier pre-commit install

### ISSUE THREAD

**Issue by esciara** [pre-commit/pre-commit.com#240]
Here is the result of installing hooks with pre-commit:

```
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
```

Would it now be a good idea to have it return a list of the hooks installed and in what stages?

For instance for the following `.pre-commit-config.yaml` file:
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
```
one would get the following messages:
```
$ pre-commit install
pre-commit installed the following hooks at .git/hooks/commit-msg:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
```

**Comment by asottile** [comment]
It might then be confusing if the user changed their configuration after that (they don't need to rerun `install`)

**Comment by asottile** [comment]
On second thought, I think this is a fine idea -- as long as it uses the word "currently" somewhere in there

maybe

```console
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit

currently configured hook(s) for the `commit` stage:
- trailing-whitespace
- end-of-file-fixer
- check-yaml
- debug-statements
```

**Comment by asottile** [comment]
actually, coming back to this -- there isn't sufficient information during hook script installation to do this (pre-commit would need to download all the hook repositories to know the stages applied for individual hooks)
