### ISSUE TITLE
Group hooks by type

### ISSUE THREAD

**Issue by brettcannon** [pre-commit/pre-commit.com#341]
It would be really handy to have the hooks grouped by what it specified in the `types` field in the JSON data. That way if I'm looking to see what hooks apply to Python I can look in that section. I would assume this would be its own `<h2>` section after the current by-repository list.

**Comment by asottile** [comment]
I think some sort of search would be better than grouping, but I'm not sure what that would look like 🤔

**Comment by brettcannon** [comment]
Maybe a filter drop-down at the top? It lists all the known types and you select one and it filters the lists down to just type matches?

**Comment by asottile** [comment]
yeah that could work -- the data is available in json so it could use that to build a search

**Comment by paulhfischer** [comment]
would you be fine if i'd implement the filter function with js?
e.g. adding a custom data-tag to each list item with the `types` value from `hooks.json` and then filtering the list according to the selection (or no filter if nothing is selected)

if yes: do you prefer inline js in `<script>...</script>` or should i put the code in an extra file?

**Comment by brettcannon** [comment]
Thanks so much to everyone who helped make this happen!

I've now submitted a couple PRs to fill out the `types` fields on some hooks to fill out the list a bit more. 😁
