### ISSUE TITLE
Should mirrors-isort be marked as deprecated in the list of hooks?

### ISSUE THREAD

**Issue by domdfcoding** [pre-commit/pre-commit.com#367]
Hi,

The readme for https://github.com/pre-commit/mirrors-isort lists the hook as deprecated, as isort itself now has its own pre-commit hook. However, on https://pre-commit.com/hooks.html the hook is not indicated as being deprecated. Should it be?

Perhaps like

![image](https://user-images.githubusercontent.com/8050853/87232047-e6fb1b80-c3b3-11ea-96a4-6474d77f4e4a.png)

or

![image](https://user-images.githubusercontent.com/8050853/87232052-ebbfcf80-c3b3-11ea-8f01-a56b30b6ae90.png)

**Comment by asottile** [comment]
the hooks.html file is generated automatically from the source -- there isn't really a way to mark that right now (and if you click through you'll see the deprecation anyway)

it still works though so shrugs?  I guess the better option would maybe be to remove it from the list

what do you think?

**Comment by domdfcoding** [comment]
Or could you put the deprecation message in the `description` field of the `.pre-commit-hooks.yaml` for mirrors-isort? That would get automatically added after the word "isort", right?

But I agree the better option is just to remove it from the list.

**Comment by asottile** [comment]
I can't really do that since the `.pre-commit-hooks.yaml` is auto generated -- removing probably  makes the most sense -- would you like to send a PR?

**Comment by domdfcoding** [comment]
Ah, makes sense. I'll have a look at making a PR now.

Loving pre-commit by the way 😁
