### ISSUE TITLE
Introduction: Please add "4. (optional) Run against a single file"

### ISSUE THREAD

**Issue by guettli** [pre-commit/pre-commit.com#445]
At the moment there is this heading on the start-page:

> 4. (optional) Run against all the files

I think running it against all files is too much at the beginning.

Why not like this?

## 5.  (optional) Run against all the files

I think this would improve the first-time-user-experience.

Thank you for this great tool!

**Comment by asottile** [comment]
> I think running it against all files is too much at the beginning.

why?  the operations are non-destructive, you can always `git checkout -- .` if they do not go according to plan

> Why not like this?

generally fewer steps is better for a quick start, the step is optional as well, and then you'd have to explain why duplicate steps

> I think this would improve the first-time-user-experience.

I disagree with this being an improvement, I think it'd make it more work to get started

___

thanks for the feedback, but I'm going to decline this suggestion
