### ISSUE TITLE
Invalid Discord invite link

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit.com#479]
The invite link from https://pre-commit.com/#getting-help doesn't work.

**Comment by asottile** [comment]
can you show what you get when you click it?  the discord side shows it is working and it's the same link that's used elsewhere

**Comment by revolter** [comment]
Sure:

![image](https://user-images.githubusercontent.com/5748627/111541389-19e28400-8779-11eb-932a-2002bf655b77.png)

**Comment by asottile** [comment]
weird! and not a super helpful error message from discord's side -- can you DM me asottile#3110 -- maybe I can send you another invite link and we can try that?

**Comment by revolter** [comment]
Hmm, I tried adding you as a friend (because I didn't find a way to DM without it), and it says that it's incorrect.

**Comment by asottile** [comment]
oh I'm bad at reading, it's 3310

**Comment by asottile** [comment]
not sure what was wrong but a direct invite worked 🤷
