### ISSUE TITLE
`pylint` supported?

### ISSUE THREAD

**Issue by ehontoria** [pre-commit/pre-commit.com#520]
Hi there, it looks like https://github.com/PyCQA/pylint now has a `.pre-commit-hooks.yaml` but it isn't listed on the website as a supported hook. Not sure whether it should be?

**Comment by asottile** [comment]
are you spelling pylint correctly? I see it https://pre-commit.com/hooks.html

**Comment by ehontoria** [comment]
Looks like searching for `pylint` wasn't working with the filter, apologies and thanks!

**Comment by ehontoria** [comment]
Actually if you search on the filter and then delete everything in the search box the list isn't all the hooks - maybe a filtering issue?

**Comment by asottile** [comment]
ah, those two are related!  I commented here: https://github.com/pre-commit/pre-commit.com/pull/512#issuecomment-856822604
