### ISSUE TITLE
Supported hooks page not listing prettier when filtering for lang JS

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit.com#537]
https://pre-commit.com/hooks doesn't show prettier if the "Filter hook type" dropdown is set to "javascript":

![Screen Shot 2021-07-21 at 07 50 13](https://user-images.githubusercontent.com/30958850/126438029-0b7b3d31-1e15-4c69-8739-921f9810e0cb.png)

![Screen Shot 2021-07-21 at 07 50 23](https://user-images.githubusercontent.com/30958850/126438056-c57c9e66-8459-450b-b212-541fafce7494.png)

**Comment by asottile** [comment]
prettier doesn't have `types: [javascript]` so it won't show up there: https://github.com/pre-commit/mirrors-prettier/blob/bc48c541add1551be726f23c4294c773442341cb/.pre-commit-hooks.yaml#L5

**Comment by janosh** [comment]
Yeah I saw that, but I think it should have type JavaScript￼. That's what people wanting to use it will most likely be searching for.

**Comment by Avasam** [comment]
https://github.com/pre-commit/mirrors-prettier/pull/34
