### ISSUE TITLE
Supported hooks page should mention when external dependency required

### ISSUE THREAD

**Issue by KindDragon** [pre-commit/pre-commit.com#560]
I like pre-commit because most off hooks require no external dependencies and everyone from my team can just use them without installing additional tools. So, it would be helpful if on page "Supported hooks" we can clearly see if the hook requires some 3rd-party depenecies.

**Comment by asottile** [comment]
it's impossible to know beyond whether it's implemented with `language: script` / `language: system` --  though ideally I should just ban any `system` / `script` hooks from that page as they would fall under "needing external tools"?

**Comment by KindDragon** [comment]
I think not. For example, this hooks https://github.com/pocc/pre-commit-hooks (they use `language: python`) require installation of additional packages to the system https://github.com/pocc/pre-commit-hooks#installation.
I think you need to extend `.pre-commit-hooks.yaml` with some field that 3rd party dependencies required for using it. More advanced solution would be installing them automatically using the right system package tool: apt, yum, dnf, pkg, pkgutil, brew and pacman depending on the system we are running.

**Comment by asottile** [comment]
running system package managers blindly from userspace is not a good idea

even those which are `language: python` but require external installation are missing the point of the framework and I should remove them

**Comment by KindDragon** [comment]
At least you can print message when user run `pre-commit run` first that you should install following run following command to use it `sudo apt install package-name`.

> even those which are language: python but require external installation are missing the point of the framework and I should remove them

Maybe move them to separate section? They still kinda useful

BTW this two also require 3rd party dependencies https://gitlab.com/pablodiehl/pre-commit-lua-formatter https://github.com/Calinou/pre-commit-luacheck . I am not sure how properly implement them as pre-commit hook if `luarocks` not installed on the system, it's require several dependecies https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix

**Comment by asottile** [comment]
for clarity, things which require external dependencies beyond the managed pre-commit environment are **using the unsupported escape hatch** and extra features / work for those will not be implemented

**Comment by KindDragon** [comment]
So, the only option here for unsupported languages like C++ or LUA is to use docker image or `repo: local`?

**Comment by asottile** [comment]
you _can_ use `script` / `system` / others which depend on external resources -- they are just not the ideal and supported pathway

**Comment by KindDragon** [comment]
Ok
