### ISSUE TITLE
Supported hooks page not listing language C++

### ISSUE THREAD

**Issue by KindDragon** [pre-commit/pre-commit.com#563]
https://pre-commit.com/hooks show several hooks for C++ like clang-format/clang-tidy/cpplint/include-what-you-use, but there no C++ in "Filter hook type:"

**Comment by asottile** [comment]
those tools don't specify `types` so they won't be listed in the types dropdown: https://github.com/pocc/pre-commit-hooks/blob/093614db90b54cca053c04de00128d70c638b4c2/.pre-commit-hooks.yaml#L10

**Comment by KindDragon** [comment]
Thanks
