### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by mxr** [pre-commit/pre-commit.com#584]
Should this repo have a license?

**Comment by asottile** [comment]
IANAL but it's not intended to be reused, redistributed, modified, etc. so I don't think it should have one?

**Comment by mxr** [comment]
There is some code (specifically install-local.py) that could be vendored, modified, etc. Does that count?

**Comment by asottile** [comment]
yeah install-local would fall into that -- I would like to remove that eventually and reserving rights on it seems appropriate

**Comment by asottile** [comment]
ah, by reserving rights I meant keep it without a license

**Comment by YoSiJo** [comment]
I would like to propose the AGPLv3.

**Comment by asottile** [comment]
nobody asked @YoSiJo 

and gpl is a cancer
