### ISSUE TITLE
Add official shellcheck hook

### ISSUE THREAD

**Issue by jebob** [pre-commit/pre-commit.com#658]
[There is an official hook for pre-commit](https://github.com/koalaman/shellcheck#pre-commit) which should be added to the [list](https://pre-commit.com/hooks.html).

There's also several unofficial implementations on that page which could be removed if desired.

**Comment by jebob** [comment]
OTOH, that hook relies on docker and therefore takes a while to run.

**Comment by asottile** [comment]
shellcheck-py is maintained by me and provides a significantly better experience
