### ISSUE TITLE
Link to `default_install_hook_types` is not correct

### ISSUE THREAD

**Issue by KAUTH** [pre-commit/pre-commit.com#746]
In https://github.com/pre-commit/pre-commit.com/blob/main/sections/cli.md#L153 (line 153)  the `default_install_hook_types` link incorrectly points to `#top_level-default_language_version`, instead of `#top_level-default_install_hook_types`.

**Comment by asottile** [comment]
send a patch please

**Comment by KAUTH** [comment]
Sending now

**Comment by asottile** [comment]
for typos don't bother with an issue

**Comment by KAUTH** [comment]
makes sense, thanks
