### ISSUE TITLE
Documentation assumes incorrectly that a tag is an immutable ref - leading to a supply-chain security risk

### ISSUE THREAD

**Issue by avri-schneider** [pre-commit/pre-commit.com#770]
In file [sections/advanced.md#L826-L827](https://github.com/pre-commit/pre-commit.com/blame/7bf4362d9296b4d512f54d71cf28f3083d89dc88/sections/advanced.md#L826-L827) states:
> `pre-commit` assumes that the value of [`rev`](#repos-rev) is an immutable ref (such as a
tag or SHA) and will cache based on that

It is incorrect to assume that a tag is an immutable ref.

See [Using third-party actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) section in the GitHub Actions security hardening guide:
> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

Please amend the documentation to state that only the full length commit SHA is an immutable ref and preferably add a similar security warning.

**Comment by asottile** [comment]
no thanks
