### ISSUE TITLE
Add sql-formatter hook

### ISSUE THREAD

**Issue by slyapustin** [pre-commit/pre-commit.com#781]
There [is](https://github.com/slyapustin/pre-commit-sql-formatter) an _unofficial_ hook for [sql-formatter](https://github.com/sql-formatter-org/sql-formatter) which might be added to the [list](https://pre-commit.com/hooks.html).

Was [trying to convince the author](https://github.com/sql-formatter-org/sql-formatter/pull/556) to add an official integration, but he is against it.

**Comment by asottile** [comment]
I don't know what you want me to do about it -- the author seems to ignore tools like [eslint](https://github.com/eslint/eslint) or [rubocop](https://github.com/rubocop/rubocop) which are orders of magnitude more popular than their tool which have set up an integration

**Comment by slyapustin** [comment]
I would like to have an alternative for sqlfluff (which is insanely slow on big SQL files) in the list https://pre-commit.com/hooks.html

sql-formatter is a nice alternative for that, and I added an integration for it: https://github.com/slyapustin/pre-commit-sql-formatter
