### ISSUE TITLE
Add `Rome` formatter as a mirror.

### ISSUE THREAD

**Issue by veritas9872** [pre-commit/pre-commit.com#794]
Hello, as a fan of pre-commit, I would first like to thank the pre-commit maintainers for their work. To further the project even more, I would like to ask for the inclusion of the `Rome` formatting library as a pre-commit hook as a mirror.

`Rome` is a popular alternative for `Prettier` and other JavaScript formatting libraries written in Rust to greatly increase the execution speed. However, there are no plans to create a pre-commit hook in the near future. https://github.com/rome/tools/discussions/4246

I believe that creating a `Rome` mirror, similar to the `Prettier` and `ESLint` mirrors in the pre-commit project would be helpful for many users.

**Comment by asottile** [comment]
it might be that they don't know how simple it'd be? perhaps if you show them the few lines of yaml needed to support it they'd be more likely?

**Comment by veritas9872** [comment]
I will try and make a commit on the Rome repository. Closing this issue for now.
