### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by quom** [pre-commit/pre-commit.com#865]
[This](https://github.com/pre-commit/pre-commit.com/blob/main/sections/new-hooks.md?plain=1#L7) line has:
> The hook must exit nonzero on failure or modify files.

Does this mean:
> The hook must (exit nonzero on failure) or (modify files).

Or:
> The hook must exit nonzero (on failure or modify files).

If it is the former using an Oxford comma would clear up the ambiguity:
> The hook must exit nonzero on failure, or modify files.

**Comment by asottile** [comment]
"on modify files" is not grammatically correct so it is unambiguous.  it would be "on modification of files"

please be pedantic elsewhere
