### ISSUE TITLE
Filter hooks by language

### ISSUE THREAD

**Issue by benediktsatalia** [pre-commit/pre-commit.com#873]
It would be interesting to be able to filter the all hooks page by language (language of the hook not the hook type). I think a list of checkboxes to tick or untick for each pre-commit language would be nice.

The use case is that basically every new language introduced to a pre-commit config means new dependencies and to reduce number of dependencies it could be interesting to only use very common languages like python. Or to not use docker due to security risks.

**Comment by asottile** [comment]
I've revamped the hooks page and removed most of the repositories so this is less relevant -- probably can take some of the examples from the [code searching](https://pre-commit.com/hooks.html#finding-hooks) section and customize your search to whatever specifics you want!
