### ISSUE TITLE
Bot keeps bumping ruff-pre-commit to incompatible release

### ISSUE THREAD

**Issue by sjlongland** [pre-commit/pre-commit.com#887]
Hi,

Firstly, great service, this tool is a great help keeping code in check.  One little irritation however, the bot seems to always choose the latest version of each hook, even when that version is incompatible with the project.

Our project targets multiple versions of Python, including some that are no longer maintained such as Python 3.6… just because 3.12 is the latest does not mean every computer with Python installed magically updates itself and some production environment are very conservative regarding updates.

(I've had to argue with a manager about Python 2.7 for example, and I have colleagues that still happily load Debian Stretch onto new boxes despite it being ancient today.)

As such, we try to limit ourselves to features supported by Python 3.6, chosen as a lower practical limit that still supports 'modern' features, whilst still allowing a wide compatibility base.

The problem is the pre-commit bot insists on bumping `ruff-pre-commit`.  The last version to support Python 3.6 is v0.0.233.  When it bumps this and proposes a pull request, the PR tests fail because… surprise surprise… the version of `ruff` used doesn't support this version of Python.

https://results.pre-commit.ci/run/github/659078614/1697485172.NGow0yyXQNaO8Fti5MGycw

https://github.com/diazona/setuptools-pyproject-migration/pull/108 is an example, where I've then had to revert one of the version bumps.

I had a look through the documentation and issues, couldn't see anywhere to "pin" a hook version.  Is there a method to pin this particular hook to a compatible version?

**Comment by asottile** [comment]
you're looking for https://github.com/pre-commit-ci-config/issues (linked on the bottom of every pre-commit *ci* page) -- there you'll find several duplicates for your query.  this is the repo for the docs for the open source tool

**Comment by sjlongland** [comment]
Errrm, that link is a 404 page.  Search is not finding any related repositories for `pre-commit-ci-config`.

**Comment by sjlongland** [comment]
Found it: https://github.com/pre-commit-ci/pre-commit-ci-config/issues

**Comment by asottile** [comment]
sorry try again, auto complete on my phone

**Comment by sjlongland** [comment]
So, closest related to this is https://github.com/pre-commit-ci/issues/issues/83#issuecomment-946140388

An idea: you might save money running the service by not having it unwittingly push broken PRs.  If I had a way to tell it "don't update ${HOOK} beyond version ${LAST_GOOD_VERSION}", it would remove the need for pre-commit CI needing to run a hook, watch it fail, have one of us push a commit that reverts the breaking change forcing pre-commit CI to run again.

I leave that for you to consider. :-)

**Comment by asottile** [comment]
:-) it doesn't
