### ISSUE TITLE
Will a hook be accepted if one of the hooks in `.pre-commit-hooks.yaml` is `system`?

### ISSUE THREAD

**Issue by braydonk** [pre-commit/pre-commit.com#888]
In the [PR Template](https://github.com/pre-commit/pre-commit.com/blob/1eda5a7f188ebdc868bcccdd15332b5f5a9996a5/.github/pull_request_template.md?plain=1#L9) it mentions that adding a hook to the list seems to require that it is not a system hook. I already have `yamlfmt` on the list, which is a Go hook.

I have [had a request](https://github.com/google/yamlfmt/issues/144) for `yamlfmt` to support a `system` hook as well. `yamlfmt` is already on the list as a Go hook. Will adding the `system` hook cause it to be breaking the rules and have yamlfmt removed from the list?

**Comment by braydonk** [comment]
Do you mean creating their own `repo: local` hook that is `system`, or that they can override a hook from another repo to be `system` instead?

**Comment by asottile** [comment]
any setting from a remote hook can be directly overriden in their personal configuration
