### ISSUE TITLE
pipx installation option

### ISSUE THREAD

**Issue by mbway** [pre-commit/pre-commit.com#946]
It might be a good idea to suggest/recommend using [pipx](https://pipx.pypa.io/stable/) to install `pre-commit` instead of `pip`?

`pre-commit` is a tool that can be used across multiple projects so installing system-wide makes more sense in most cases.

**Comment by asottile** [comment]
please search the issue tracker next time

**Comment by mbway** [comment]
sorry. I did search, but on `pre-commit/pre-commit` by mistake

**Comment by asottile** [comment]
there are, try again

**Comment by mbway** [comment]
I mean this repo specifically. I see now that there are at https://github.com/pre-commit/pre-commit. Again, sorry for bothering you

**Comment by asottile** [comment]
yes this repo #421 for example
