### ISSUE TITLE
Can we have a CONTRIBUTING.md document?

### ISSUE THREAD

**Issue by Flimm** [pre-commit/pre-commit.com#975]
Are contributions to documentation welcome in this repo?

- Are small pull requests welcome? Here's an example: https://github.com/pennersr/django-allauth/pull/3895/files Would this be welcome in this repo? In my experience, these pull requests get accepted quickly, as they are quick to review, but on one or two occasions, the pull requests were closed immediately. I guess they seemed like spam. I don't want to make an open source contributor feel spammed. I am happy to make the effort to explain the changes in the pull request description, if that is what is needed. If it's not needed, I'm happy to save myself that time.
- Are big pull requests to documentation welcome? Some improvements to documentation can't be done well in small bites.
- If pull requests aren't welcome, are other types of feedback welcome, such as GitHub issues? Can GitHub issues be converted to pull requests to the documentation, or are GitHub issues considered documentation in themselves?

It would be useful if potential contributors were directed to CONTRIBUTING.md. Right now, there isn't any guidance on how to contribute documentation.

Funnily enough, this issue is in itself a request for documentation :)

I find your work impressive, and I want to make it more accessible to people like me, and to people with even less experience than me.

**Comment by asottile** [comment]
we haven't needed one because generally people make reasonable contributions

I don't think you're acting in good faith

**Comment by asottile** [comment]
I'm going to temporarily limit your ability to interact because you need some time to think about how you're approaching things and clearly my attempts to tell you that are not working
