### ISSUE TITLE
Selectively skipping pre-commit hooks on Windows

### ISSUE THREAD

**Issue by Redjest** [pre-commit/pre-commit.com#987]
Hi, thanks for maintaining pre-commit, I use it daily and love it (:

In the docs there's a way to skip a certain hook - super useful:
```bash
SKIP=flake8 git commit -m "foo" 
```
This of course will work on Linux and MacOS, but not on Windows.

The Windows version will be:
```cmd
$env:SKIP="flake8"; git commit -m "foo"
```
Might be useful for some users

**Comment by asottile** [comment]
that's for PowerShell specifically.  the original I believe works fine in batch

**Comment by Redjest** [comment]
Surly you can install bash on Windows and use a bash flavor of the command, the use cases I had in mind were either when pre-commit runs on a CI pipelines on which this kind of trick might be challenging for some users, or for users using Windows native CLIs (cmd, PowerShell)

**Comment by asottile** [comment]
read closely I didn't say bash

**Comment by Redjest** [comment]
If by batch (as in batch files) you mean the Windows CMD, the line would be:
```cmd
set SKIP=flake8 && git commit -m "foo"
```

The Linux command would return:
```
'SKIP' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by asottile** [comment]
neither that nor what you wrote above is equivalent or temporary

**Comment by Redjest** [comment]
Agree, you need to unset the `SKIP` explicitly if you want exactly the same behavior.

PowerShell:
```PowerShell
$env:SKIP="flake8"; pre-commit run --all-files; $env:SKIP=$null
```

CMD:
```cmd
set SKIP=flake8 && pre-commit run -a && set SKIP="" 
```

**Comment by Redjest** [comment]
`env SKIP=flake8 pre-commit ...` works on neither PowerShell or CMD. 
Didn't ask for guidance, the examples I showed here work, just hoped to save a few minutes for others in the future.
I thought a version of the command that works on Windows will be useful for some devs.

**Comment by asottile** [comment]
works great for me in both but you do you
